upstream php-fpm-backend {
    least_conn;
    server php_fpm_1:9000;
    server php_fpm_2:9000;
}

server {
    listen 80;
    server_name weather.monitor;
    root /var/www/html;          # Совпадает с volume
    index index.php index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    # Ключевой блок: передаёт .php в fpm
    location ~ \.php$ {
        fastcgi_pass php-fpm-backend;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /var/www/src$fastcgi_script_name;
    }
}
