[PHP]
memory_limit = 256M
max_execution_time = 300
max_input_time = 300
max_input_vars = 2000
post_max_size = 128M
upload_max_filesize = 128M
date.timezone = UTC
display_errors = On
display_startup_errors = On
error_reporting = E_ALL
error_log = /var/log/php/error.log
log_errors = On

[opcache]
opcache.enable = 1
opcache.memory_consumption = 128
opcache.interned_strings_buffer = 8
opcache.max_accelerated_files = 4000
opcache.revalidate_freq = 0
opcache.validate_timestamps = 1

[redis]
extension=redis.so

[memcached]
extension=memcached.so